services:
  cloudgram-go:
    container_name: cloudgram-go
    image: irorikon/cloudgram-go:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "5244:5244"
    environment:
      - LISTEN=<:5244>
      - AUTH_USER=<string>
      - AUTH_PASSWORD=<string>
      - TELEGRAM_BOT_TOKEN=<string>
      - DB_TYPE=<mysql|postgres|sqlite>
      - DB_DSN=<string>
      - LOG_PATH=<string>
      - JWT_SECRET_KEY=<string>
      - DEBUG=<true|false>